input {
  file {
    path => "/mnt/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    columns => ["id", "title", "genres", "original_language", "overview", "popularity", "production_companies", "release_date", "budget", "revenue", "runtime", "status", "tagline", "vote_average", "vote_count", "credits", "keywords", "poster_path"]
    skip_header => true
  }

  mutate {
    split => { "genres" => "|" }
    split => { "keywords" => "|" }
    split => { "production_companies" => "|" }
    split => { "credits" => "|" }
  }

  mutate {
    convert => { 
      "budget" => "float"
      "revenue" => "float"
      "runtime" => "integer"
      "vote_average" => "float"
      "vote_count" => "integer"
      "popularity" => "float"
    }
  }

  date {
    match => [ "release_date", "dd/MM/yyyy", "yyyy-MM-dd" ]
    target => "release_date"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_clean"
  }
  stdout { codec => rubydebug }
}