# Chemin vers le fichier à l'intérieur du container Docker
input {
  file {
    path => "/mnt/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  # 1. Analyse du format CSV
  csv {
    separator => ","
    columns => ["id", "title", "genres", "original_language", "overview", "popularity", "production_companies", "release_date", "budget", "revenue", "runtime", "status", "tagline", "vote_average", "vote_count", "credits", "keywords", "poster_path"]
    skip_header => true
  }

  # 2. Nettoyage des listes (Normalisation F3)
  # On transforme "Action|Drama" en une vraie liste ["Action", "Drama"]
  mutate {
    split => { "genres" => "|" }
    split => { "keywords" => "|" }
    split => { "production_companies" => "|" }
    split => { "credits" => "|" }
  }

  # 3. Conversion des types (F3)
  # On transforme le texte d'Excel en vrais nombres
  mutate {
    convert => { 
      "budget" => "float"
      "revenue" => "float"
      "runtime" => "integer"
      "vote_average" => "float"
      "vote_count" => "integer"
      "popularity" => "float"
    }
  }

  # 4. Traitement de la date (F3)
  # On transforme les dates en format Date utilisable par Kibana
  date {
    match => [ "release_date", "dd/MM/yyyy", "yyyy-MM-dd" ]
    target => "release_date"
    tag_on_failure => [] 
  }
}

output {
  # Envoi vers Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_clean"
  }
  
  # Affiche le résultat dans ton terminal Docker pour vérifier que ça tourne
  stdout { codec => rubydebug }
}