input {
  file {
    # On dit à Logstash de lire le fichier CSV
    path => "/usr/share/logstash/data/movies.csv"

On lui dit de commencer à lire depuis la première ligne
    start_position => "beginning"

Indispensable en phase de test pour qu'il relise le fichier à chaque fois qu'on relance
    sincedb_path => "/dev/null"
  }
}

filter {
  # On explique à Logstash que c'est un fichier CSV
  csv {
    separator => "," # Remplace par ";" si ton CSV utilise des points-virgules
    autodetect_column_names => true # Logstash va lire la 1ère ligne pour trouver les noms des colonnes
  }
}

output {
  # On envoie les données vers la base de données
  elasticsearch {
    hosts => ["http://elasticsearch:9200/"] # L'adresse de l'Elasticsearch que tu as créé dans Docker
    index => "movies_raw" # Le nom de l'index (la table) demandé pour la F2
  }

Optionnel mais super utile : ça affiche les données dans le terminal pour vérifier que ça marche !
  stdout { 
    codec => rubydebug 
  }
}